services:
  - type: web
    name: student-marks-predictor
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn prediction_marks:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
